### ISSUE TITLE
only showing first section in 'select resource' dialogue

### ISSUE THREAD

**Issue by mikeatcityuni** [tonyjbutler/moodle-mod_aspirelist#3] opened 2015-08-03 09:54 UTC
Hi, not sure if a change in Aspire may have caused this but we are currently only able to see resources from section #1 when adding reading list items. 

Using code for Moodle 2.8 2015012102 

![image](https://cloud.githubusercontent.com/assets/4233765/9035230/f81f3a6a-39cd-11e5-8bd6-b87a0c9e9680.png)

**Comment by tonyjbutler** [comment] 2015-08-03 10:46
Thanks Mike.

This started just over a week ago and is caused by malformed HTML in the Aspire lists themselves (view the same list in Chrome and IE, and observe the difference in the way the different browsers interpret the broken structure).

Feel free to add your input/support at http://support.talis.com/requests/9747 to get this resolved more quickly.

Cheers,
Tony

**Comment by mikeatcityuni** [comment] 2015-08-03 11:55
ah, I suspected as much ... I cannot access that request though, shall I log separately?

**Comment by tonyjbutler** [comment] 2015-08-03 13:06
Sure, it couldn't hurt.

**Comment by mikeatcityuni** [comment] 2015-08-14 09:54
Hi Tony, Talis are saying this is fixed but I still see the issue. Do you?

"Yesterday we made a released which should now have resolved the issue with sections displaying in your integrations with the Learning Management Systems using LTI."

**Comment by tonyjbutler** [comment] 2015-08-14 10:17
Yep, it's definitely not fixed, and they haven't marked the issue I raised with them as resolved.

They seem to be referring to an LTI integration in that quote above. Did you raise a separate issue at some point with their LTI integration?

**Comment by mikeatcityuni** [comment] 2015-08-14 11:09
No, I clearly stated that we were using your integration.

**Comment by tonyjbutler** [comment] 2015-08-14 13:24
They obviously need it explaining to them again.

**Comment by tonyjbutler** [comment] 2015-08-25 14:12
The priority of my Talis support request to get this fixed has now been escalated to 'Urgent'.

**Comment by mikeatcityuni** [comment] 2015-09-08 14:14
Hi, just back from hols and checking in for an update ... did urgent mean it got fixed already?

**Comment by tonyjbutler** [comment] 2015-09-08 14:22
I'm afraid not -- they're still working on it. Are you City University London by the way? I've asked Talis to give you access to the support request (and a couple of other institutions).

**Comment by mikeatcityuni** [comment] 2015-09-08 14:37
Hi, yes at City ... they emailed on 27th to say "There has been an issue reported by Lancaster that we are looking into. It is worth noting that Tony Butler's integration is not one that we support but we are working with Lancaster to try to resolve this for all those customers that are using the plugin.
I've linked your ticket to the Lancaster ticket although you won't be able to see this ticket we will keep you updated on progress."

**Comment by tonyjbutler** [comment] 2015-09-08 14:51
Nice and transparent ;-)

**Comment by mikeatcityuni** [comment] 2015-09-15 10:59
Hi, it's fixed!

**Comment by tonyjbutler** [comment] 2015-09-15 11:57
Almost. There's still an issue with the display of section data when viewing the list, which I've just fixed (and I see you've reported this as a separate issue so I'll now close this one).

**Closed as completed by tonyjbutler** 2015-09-15 11:57 UTC
